Update build-apk.yml

diff --git a/.github/workflows/build-apk.yml b/.github/workflows/build-apk.yml
--- a/.github/workflows/build-apk.yml
+++ b/.github/workflows/build-apk.yml
@@ -16,21 +16,33 @@ jobs:
           mkdir game
           unzip -q vkusno-game-github-apk.zip -d game
 
-      - name: Setup Node
+      - name: Find project folder
+        run: |
+          PROJECT_DIR=$(find game -name package.json -type f -printf '%h\n' | head -1)
+
+          if [ -z "$PROJECT_DIR" ]; then
+            echo "package.json not found!"
+            exit 1
+          fi
+
+          echo "Project found: $PROJECT_DIR"
+          echo "PROJECT_DIR=$PROJECT_DIR" >> "$GITHUB_ENV"
+
+      - name: Setup Node.js
         uses: actions/setup-node@v4
         with:
-          node-version: 20
+          node-version: 24
 
       - name: Install dependencies
-        working-directory: game
+        working-directory: ${{ env.PROJECT_DIR }}
         run: npm install
 
-      - name: Add Android
-        working-directory: game
+      - name: Add Android platform
+        working-directory: ${{ env.PROJECT_DIR }}
         run: npx cap add android
 
       - name: Sync Android
-        working-directory: game
+        working-directory: ${{ env.PROJECT_DIR }}
         run: npx cap sync android
 
       - name: Setup Java
@@ -40,11 +52,13 @@ jobs:
           java-version: '17'
 
       - name: Build APK
-        working-directory: game/android
-        run: chmod +x gradlew && ./gradlew assembleDebug
+        working-directory: ${{ env.PROJECT_DIR }}/android
+        run: |
+          chmod +x gradlew
+          ./gradlew assembleDebug
 
       - name: Upload APK
         uses: actions/upload-artifact@v4
         with:
           name: vkusno-game-apk
-          path: game/android/app/build/outputs/apk/debug/app-debug.apk
+          path: ${{ env.PROJECT_DIR }}/android/app/build/outputs/apk/debug/app-debug.apk
